name: Frontend Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: hamza-khan.com-resume-site
  DISTRIBUTION_ID: ${{ vars.AWS_DISTRIBUTION_ID }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync static site to S3
        run: aws s3 sync frontend s3://${S3_BUCKET} --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/*"
